export const SET_REDIRECT ='SET_REDIRECT';
export const RESET_APP='RESET_APP';
export const SENT_TRUE='SENT_TRUE';
export const SET_LOADING ='SET_LOADING';
export const UPDATE_FILENAMES ='UPDATE_FILENAMES';

export const ADD_SELECTED ="ADD_SELECTED";
export const REMOVE_SELECTED ="REMOVE_SELECTED";


