export const SET_REDIRECT ='SET_REDIRECT';
export const RESET_APP='RESET_APP';
export const SENT_TRUE='SENT_TRUE';
export const SET_LOADING ='SET_LOADING';
export const SET_RESET ='SET_RESET';
export const UPDATE_FILENAMES ='UPDATE_FILENAMES';
export const GOT_DATA ="GOT_DATA";

export const ADD_SELECTED ="ADD_SELECTED";
export const REMOVE_SELECTED ="REMOVE_SELECTED";
export const CLEAR_SELECTED ="CLEAR_SELECTED";

export const UPDATE_IMAGE_PAIRS = "UPDATE_IMAGE_PAIRS";
export const UPDATE_IMAGE_SIZE = "UPDATE_IMAGE_SIZE";
export const UPDATE_PROCESSING_TIME = "UPDATE_PROCESSING_TIME";
export const UPDATE_IMAGE_NAMES ="UPDATE_IMAGE_NAMES";


